### ISSUE TITLE
Example code for the course won't initialize

### ISSUE THREAD

**Issue by douglas-man** [eugenp/course#6]
Dear Sir,

I have tried the first example by including jetty plug-in in the Pom file but the example code is given an no existed path to @ComponentScan and no definition were given for the properties values for the @importresources

Or I m a complete idiot

**Comment by eugenp** [comment]
Hey @douglas-man - sorry for the late response on this one. I was reading (and re-reading) your question here and I am not sure I fully understand it. 
Can you explain a bit more in-depth exactly what you're trying to do, and what's not working. 
Also, specify the exact lesson you're looking at - because, as I'm sure you've seen - the course is structured in many modules. 
Cheers, 
Eugen.

**Comment by douglas-man** [comment]
Oh Thank You For Replying, I Should Have Checked Here More Often...
I've been trying section1/s1_vid1...

At the end of mvn jetty:run,...

2016-08-02 15:08:01,241 [main] ERROR o.s.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [/home/dman/Documents/course/section1/s1_vid1/target/classes/com/packt/springsecurity/frontend/spring/ClientContextConfig.class]; nested exception is java.lang.IllegalArgumentException

I've modified the pom.xml to use jetty...

			<plugin>
				<groupId>org.eclipse.jetty</groupId>
				<artifactId>jetty-maven-plugin</artifactId>
				<version>9.3.8.v20160314</version>

I
[INFO] Configuring Jetty for project: spring-security
[INFO] Webapp source directory = /home/dman/Documents/course/section1/s1_vid1/src/main/webapp
[INFO] Reload Mechanic: automatic
[INFO] Classes = /home/dman/Documents/course/section1/s1_vid1/target/classes
[INFO] Context path = /
[INFO] Tmp directory = /home/dman/Documents/course/section1/s1_vid1/target/tmp
[INFO] Web defaults = org/eclipse/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
[INFO] web.xml file = /home/dman/Documents/course/section1/s1_vid1/src/main/webapp/WEB-INF/web.xml
[INFO] Webapp directory = /home/dman/Documents/course/section1/s1_vid1/src/main/webapp
[INFO] jetty-9.3.8.v20160314
[INFO] No Spring WebApplicationInitializer types detected on classpath
[INFO] Initializing Spring root WebApplicationContext
2016-08-02 15:08:01,114 [main] INFO  o.s.web.context.ContextLoader - Root WebApplicationContext: initialization started
2016-08-02 15:08:01,167 [main] INFO  o.s.w.c.s.AnnotationConfigWebApplicationContext - Refreshing Root WebApplicationContext: startup date [Tue Aug 02 15:08:01 EDT 2016]; root of context hierarchy
2016-08-02 15:08:01,217 [main] INFO  o.s.c.a.ClassPathBeanDefinitionScanner - JSR-250 'javax.annotation.ManagedBean' found and supported for component scanning
2016-08-02 15:08:01,217 [main] INFO  o.s.c.a.ClassPathBeanDefinitionScanner - JSR-330 'javax.inject.Named' annotation found and supported for component scanning
2016-08-02 15:08:01,241 [main] ERROR o.s.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [/home/dman/Documents/course/section1/s1_vid1/target/classes/com/packt/springsecurity/frontend/spring/ClientContextConfig.class]; nested exception is java.lang.IllegalArgumentException

**Comment by eugenp** [comment]
Hey @douglas-man - that's interesting. The code is mostly tested and validated for Tomcat, so my suggestion (unless you really need some Jetty specific functionality) is to go through the material with it. 
Also, keep in mind that the code is slightly older now, so it's a good idea to use the Tomcat 7 version of the server. 
Let me know. Cheers, 
Eugen.

**Comment by douglas-man** [comment]
Thank You for diligently responding to me.  I am after all a complete  idiot.  I've gotten the project to build and run with jetty maven plugin.  It was a version out of sync issue between jetty and jdk...

**Comment by eugenp** [comment]
Cool, glad everything is sorted out. Cheers,
Eugen.
